config/routes.rb
Rails.application.routes.draw do  
  devise_for :users
  root to: 'items#index'

  # 商品
  resources :items do
    put :favorite, on: :member
  end


  
  # 使用者
  resources :users do
    collection do
      post :usertosale
      get :userfavorite
      get :useritem
    end
  end



  # 訂單
  resources :orders do
    collection do
      post :addtoorder
    end
  end

   # 聊天
  resources :conversations do
    member do
      post :close
    end
    resources :messages, only: [:create]
  end

  # 後台管理
  namespace :admin do
      resources :items do
        member do        
          post  :publish
          post  :hide
        end
      end
      resources :users do
        member do
          post :nottosale
          post :nottoadmin
          post :tosale
          post :toadmin
        end
      end
  end
  

  mount ActionCable.server => '/cable'  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/item.rb
class Item < ApplicationRecord
    resourcify
    belongs_to :user, optional: true

    has_many :conversations
    has_many :orders

    has_many :wlists, :dependent => :destroy
    has_many :favorited_by, through: :wlists, source: :user

    mount_uploader :picture, PictureUploader    
    
    def user_email
        user.email
    end

    private
    def product_params
      params.require(:item).permit(:picture)
    end
end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController
  before_action :set_admin_item, only: [:show, :edit, :update, :destroy]
  load_and_authorize_resource

  # GET /items
  # GET /items.json

  # def favorite
  #   type = params[:type]
  #   if type == "favorite"
  #           if 
  #             current_user.favorites.include?(@item)
  #           else
  #             current_user.favorites << @item
  #           end
  #   elsif type == "unfavorite"
  #       current_user.favorites.delete(@item)
  #   end
  # end

  def index
    if params[:search]
      @items = Item.where('name LIKE ? OR  category LIKE ?', "%#{params[:search]}%",  "%#{params[:search]}%")
      # session[:conversations] ||= []
      # @conversations = Conversation.all.where(id: @items.ids)
      # @conversations = Conversation.includes(:recipient, :messages).find(session[:conversations])
    else
      @items = Item.all
    end 

  end

  def publish
    @item.status = true
    @item.save
    redirect_to admin_items_path
  end

  def hide
    @item.status = false
    @item.save
    redirect_to admin_items_path
  end

  # GET /items/1
  # GET /items/1.json
  def show
    respond_to do |format|
      format.html
      format.js
    end
  end

  # GET /items/new
  def new
    # @item = Item.new
  end

  # GET /items/1/edit
  def edit
  end

  # POST /items
  # POST /items.json
  # def create
  #   @item = current_user.item.build(admin_item_params)

  #   respond_to do |format|
  #     if @item.save
  #       format.html { redirect_to users_path, notice: '商品建立成功' }
  #       # format.json { render :show, status: :created, location: @item }
  #     else
  #       format.html { render :new }
  #       format.json { render json: @item.errors, status: :unprocessable_entity }
  #     end
  #   end
  # end

  # PATCH/PUT /items/1
  # PATCH/PUT /items/1.json
  def update
    respond_to do |format|
      if @item.update(admin_item_params)
        format.html { redirect_to admin_items_path, notice: '商品修改成功' }
        # format.json { render :show, status: :ok, location: @item }
      else
        format.html { render :edit }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /items/1
  # DELETE /items/1.json
  def destroy
    @item.destroy
    respond_to do |format|
      format.html { redirect_to admin_items_path, notice: '成功刪除商品' }
      format.js # destroy.js.erb
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_admin_item
      @item = Item.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def admin_item_params
      params.require(:item).permit(:name, :description, :status, :amount, :price, :picture, :category, :user_id )
    end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :authenticate_user!, :except => [:index, :show]
  before_action :set_item, only: [:show, :edit, :update, :destroy]
  load_and_authorize_resource

  # GET /items
  # GET /items.json

  def favorite
    type = params[:type]
    if type == "favorite"
            if 
              current_user.favorites.include?(@item)
            else
              current_user.favorites << @item
            end
    elsif type == "unfavorite"
        current_user.favorites.delete(@item)
    end
  end

  def index
    if params[:search]
      @items = Item.where('name LIKE ? OR  category LIKE ?', "%#{params[:search]}%",  "%#{params[:search]}%")
      # session[:conversations] ||= []
      # @conversations = Conversation.all.where(id: @items.ids)
      # @conversations = Conversation.includes(:recipient, :messages).find(session[:conversations])
    else
      # @items = Item.full_joins(:orders).where.not(orders: {status: 2} )
      # @items = Item.joins('LEFT OUTER JOIN "orders"').where(orders: {status: 2} )
      # @items = Order.joins("LEFT JOIN items ON items.id = orders.item_id ").where.not(orders: {status: 2} )
      @items = Item.all.where(status: true) 
    end 


  end

  # GET /items/1
  # GET /items/1.json
  def show
    respond_to do |format|
      format.html
      format.js
    end
  end

  # GET /items/new
  def new
    @item = Item.new
  end

  # GET /items/1/edit
  def edit
  end

  # POST /items
  # POST /items.json
  def create
    @item = current_user.item.build(item_params)

    respond_to do |format|
      if @item.save
        format.html { redirect_to users_path, notice: '商品建立成功' }
        # format.json { render :show, status: :created, location: @item }
      else
        format.html { render :new }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /items/1
  # PATCH/PUT /items/1.json
  def update
    respond_to do |format|
      if @item.update(item_params)
        format.html { redirect_to users_path, notice: '商品修改成功' }
        # format.json { render :show, status: :ok, location: @item }
      else
        format.html { render :edit }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /items/1
  # DELETE /items/1.json
  def destroy
    @item.destroy
    respond_to do |format|
      # format.html { redirect_to :back, notice: '成功刪除商品' }
      format.js # destroy.js.erb
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_item
      @item = Item.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def item_params
      params.require(:item).permit(:name, :description, :status, :amount, :price, :picture, :category, :user_id )
    end
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/admin/items/_form.html.erb
<style>

    .file-upload-wrapper {
      position: relative;
      width: 100%;
      height: 60px;
    }
    .file-upload-wrapper:after {
      content: attr(data-text);
      font-size: 12px;
      position: absolute;
      top: 0;
      left: 0;
      background: #fff;
      padding: 1px 5px;
      display: block;
      width: calc(100% - 40px);
      pointer-events: none;
      z-index: 20;
      height: 40px;
      line-height: 40px;
      color: #999;
      border-radius: 5px 10px 10px 5px;
      font-weight: 300;
    }
    .file-upload-wrapper:before {
      content: '上傳';
      position: absolute;
      top: 0;
      right: 0;
      display: inline-block;
      height: 40px;
      background: #DE5E59;
      color: #fff;
      font-weight: 400;
      z-index: 25;
      font-size: 16px;
      line-height: 42px;
      padding: 0 15px;
      text-transform: uppercase;
      pointer-events: none;
      border-radius: 0 5px 5px 0;
    }
    .file-upload-wrapper:hover:before {
      background: #cc6666;
    }
    .file-upload-wrapper input {
      opacity: 0;
      position: absolute;
      top: 0;
      right: 0;
      bottom: 0;
      left: 0;
      z-index: 99;
      height: 40px;
      margin: 0;
      padding: 0;
      display: block;
      cursor: pointer;
      width: 100%;
    }

</style>

<%= form_for(@item, url: admin_item_path(@item),  html: { method: :put }) do |form| %>
  <% if item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(item.errors.count, "error") %> prohibited this item from being saved:</h2>

      <ul>
      <% item.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

<div class="row">

  <div class="col-md-6">

      <div class="field">
          <%= form.label :商品圖片： %><br>
          <%= form.file_field :picture, id: :item_picture, onchange: "readURL(this);", class:"btn btn-primary" %>
            <img id="img_prev" src="#" />
      </div>

      <script>
          function readURL(input) {
            if (input.files && input.files[0]) {
              var reader = new FileReader();
 
    
              reader.onload = function (e) {
                $('#img_prev')
                  .attr('src', e.target.result)
                  .width("100%")
                  .height("100%");
              };
              reader.readAsDataURL(input.files[0]);
            }
          }
        </script>

  </div>

  <div class="col-md-6">

    <div class="form-group">
     <%= form.label :商品名稱： %>
     <%= form.text_field :name, id: :item_name,:class => 'form-control' %>
    </div>

<div class="row">
    <div class="form-group col-xs-6">
        <%= form.label :商品分類： %>
        <%= form.select 'category', options_for_select(["二手書", "服務、票券", "居家生活", "男女包鞋服飾", "3C數位周邊","其他類別" ],"其他類別"), {}, :class => 'form-control' %>
    </div>

    <div class="form-group col-xs-6">
      <%= form.label :商品狀態： %>
      <%= form.select 'status', options_for_select(["全新", "二手"]), {}, :class => 'form-control' %>
    </div>
</div>

<div class="row">
    <div class="form-group col-xs-6">
      <%= form.label :商品數量： %>
      <%= form.number_field :amount, id: :item_amount,:class => 'form-control' %>
    </div>

    <div class="form-group col-xs-6">
      <%= form.label :商品價格： %>
      <%= form.number_field :price, id: :item_price,:class => 'form-control' %>
  </div>
</div>


    <div class="form-group">
      <%= form.label :商品描述： %>
      <%= form.text_area :description, id: :item_description,:class => 'form-control' %>
    </div><br>


    <div class="actions">
      <%= form.submit "更新" ,class: "btn btn-primary btn-sm"%>
      <%= link_to '返回', admin_items_path ,class: "btn btn-primary btn-sm" %>      
   </div>

  </div>

</div>
<% end %>
 

app/views/admin/items/edit.html.erb
<h1>新增商品</h1>

<%= render 'admin/items/form', item: @item %>

app/views/admin/items/index.html.erb
<b><%= link_to '使用者後台', admin_users_path, class: "btn btn-primary btn-lg" %></b>

<hr>

<div class="row">
    
    <div class="col-md-12">
      <table id="myTable" class="table table-sm table-hover dt-responsive" cellspacing="0" width="100%">
        <thead>
          <tr>
              <th>圖片</th>
              <th>名稱</th>
              <th>分類</th>
              <th>數量</th>
              <th>價格</th>
              <th>狀態</th>
              <th>擁有者</th>
              <th>處理</th>
          </tr>
        </thead>
        <tbody>
          <% @items.each do |item| %>
            <tr>
              <td><img src="<%= item.picture_url(:thumb) %>" width="100" height="100"></td>
              <td><%= item.name %></td>
              <td><%= item.category %></td>
              <td><%= item.amount %></td>
              <td><%= item.price %></td>
              <% if item.status == false %>
              <td style="color:red">下架</td>
              <% else %>
              <td style="color:green">上架</td>
              <% end %>
              <td><%= item.user.email %></td>
              <td>
                <% if item.status == false %>
                  <%= link_to '上架', publish_admin_item_path(item), method: :post, class: "btn btn-primary btn-sm" %>                                
                <% else %>
                  <%= link_to '下架', hide_admin_item_path(item), method: :post, class: "btn btn-primary btn-sm" %>                
                <% end %>
                <%= link_to '修改', edit_admin_item_url(item) , class: "btn btn-info btn-sm" %>
                <%= link_to '刪除', admin_item_path(item), method: :delete, class: "btn btn-danger btn-sm", data: { confirm: 'Are you sure?' },  :remote => true %>										
              </td>
    

            </tr>
              <% end %>
        </tbody>
      </table>
    </div>
    
    
    
    </div>   <!-- row -->