config/routes.rb
Rails.application.routes.draw do  
  devise_for :users
  root to: 'items#index'

  # 商品
  resources :items do
    put :favorite, on: :member
  end


  
  # 使用者
  resources :users do
    collection do
      post :usertosale
      get :userfavorite
      get :useritem
    end
  end



  # 訂單
  resources :orders do
    collection do
      post :addtoorder
    end
  end

   # 聊天
  resources :conversations do
    member do
      post :close
    end
    resources :messages, only: [:create]
  end

  # 後台管理
  namespace :admin do
      resources :items do
        member do        
          post  :publish
          post  :hide
        end
      end
      resources :users do
        member do
          post :nottosale
          post :nottoadmin
          post :tosale
          post :toadmin
        end
      end
  end
  

  mount ActionCable.server => '/cable'  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
  resourcify
  rolify
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :item 

  has_many :wlists, :dependent => :destroy
  has_many :favorites, through: :wlists, source: :item

  has_many :messages
  has_many :conversations
  has_many :orders
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < AdminController
    before_action :set_admin_user, only: [:show, :edit, :update, :destroy]
    load_and_authorize_resource
  
    # GET /users
    # GET /users.json
    def index
      @users = User.all
    end
  
    #我要當賣家
    def tosale
      current_user.add_role :sale
      redirect_to admin_users_path
    end

    def nottosale
      current_user.remove_role :sale      
      redirect_to admin_users_path
    end

    def toadmin
      current_user.add_role :admin
      redirect_to admin_users_path
    end

    def nottoadmin
      current_user.remove_role :admin      
      redirect_to admin_users_path
    end
    
    # GET /users/1
    # GET /users/1.json
    def show
    end
  
    # GET /users/new
    # def new
    #   @user = user.new
    # end
  
    # GET /users/1/edit
    def edit
    end
  
    # POST /users
    # POST /users.json
    # def create
    #   @user = current_user.user.build(admin_user_params)
  
    #   respond_to do |format|
    #     if @user.save
    #       format.html { redirect_to @user, notice: 'user was successfully created.' }
    #       format.json { render :show, status: :created, location: @user }
    #     else
    #       format.html { render :new }
    #       format.json { render json: @user.errors, status: :unprocessable_entity }
    #     end
    #   end
    # end
  
    # PATCH/PUT /users/1
    # PATCH/PUT /users/1.json
    def update
      respond_to do |format|
        if @user.update(admin_user_params)
          format.html { redirect_to @user }
          format.json { render :show, status: :ok, location: @user }
        else
          format.html { render :edit }
          format.json { render json: @user.errors, status: :unprocessable_entity }
        end
      end
    end
  
    # DELETE /users/1
    # DELETE /users/1.json
    # def destroy
    #   @user.destroy
    #   respond_to do |format|
    #     # format.html { redirect_to users_url, notice: 'user was successfully destroyed.' }
    #     format.json { head :no_content }
    #   end
    # end
  
    private
      # Use callbacks to share common setup or constraints between actions.
      # def set_user
      #   @user = current_user.find(params[:id])
      # end

      def set_admin_user
        @user = User.find(params[:id])
      rescue
        redirect_to root_path, notice: "查無此候選人"
      end
  
      # Never trust parameters from the scary internet, only allow the white list through.
      def admin_user_params
        params.require(:user).permit(:email, :encrypted_password )
      end  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    before_action :authenticate_user!
    # before_action :set_user, only: [:show, :edit, :update, :destroy]
    load_and_authorize_resource
  
    # GET /users
    # GET /users.json
    def index
      @buyorders = Order.where(buyller_id: current_user) #待確認訂單
      @sellorders = Order.where(seller_id: current_user) #待確認訂單
    end
  
    #我要當賣家
    def usertosale
      @user = User.find(params[:id])      
      current_user.add_role :sale
      redirect_to users_path
    end

    def useritem
      @user = current_user
    end

    def userfavorite
      @items = Item.all   
    end

    
    # GET /users/1
    # GET /users/1.json
    def show
    end
  
    # GET /users/new
    # def new
    #   @user = user.new
    # end
  
    # GET /users/1/edit
    def edit
    end
  
    # POST /users
    # POST /users.json
    # def create
    #   @user = current_user.user.build(user_params)
  
    #   respond_to do |format|
    #     if @user.save
    #       format.html { redirect_to @user, notice: 'user was successfully created.' }
    #       format.json { render :show, status: :created, location: @user }
    #     else
    #       format.html { render :new }
    #       format.json { render json: @user.errors, status: :unprocessable_entity }
    #     end
    #   end
    # end
  
    # PATCH/PUT /users/1
    # PATCH/PUT /users/1.json
    def update
      @user = User.find(params[:id])      
      respond_to do |format|
        if @user.update(user_params)
          format.html { redirect_to @user }
          format.json { render :show, status: :ok, location: @user }
        else
          format.html { render :edit }
          format.json { render json: @user.errors, status: :unprocessable_entity }
        end
      end
    end
  
    # DELETE /users/1
    # DELETE /users/1.json
    # def destroy
    #   @user.destroy
    #   respond_to do |format|
    #     # format.html { redirect_to users_url, notice: 'user was successfully destroyed.' }
    #     format.json { head :no_content }
    #   end
    # end
  
    private
      # Use callbacks to share common setup or constraints between actions.
      # def set_user
      #   @user = current_user.find(params[:id])
      # end

      # def set_user
      #   @user = User.find(params[:id])
      # end
  
      # Never trust parameters from the scary internet, only allow the white list through.
      def user_params
        params.require(:user).permit(:email, :encrypted_password )
      end  
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_userpanel.html.erb
<ul class="nav nav-pills nav-stacked" style="background-color:white;">
        <li role="presentation"><%= link_to "我的帳號", users_path %></li>
        <li role="presentation"><%= link_to "我的商店", useritem_users_path %></li>        
        <li role="presentation"><%= link_to "我的喜愛清單", userfavorite_users_path %></li>
        <li role="presentation"><%= link_to "我的訂單", orders_path %></li>
</ul>

app/views/users/index.html.erb
<div class="col-md-2">

		<%= render partial: 'users/userpanel' %>	
		
</div>


<div class="col-md-10">

					<div align="center" class="fh5co-pricing-table">
							<h3><%= current_user.email %></h3>
							<ul class="fh5co-list-check">
								<li class="fh5co-include">最後登入：<%= current_user.last_sign_in_at %></li>
								<li class="fh5co-include">登入次數：<%= current_user.sign_in_count %></li>
								<li class="fh5co-include">買家評價：</li>
								<li class="fh5co-include">賣家評價：</li>
								
							</ul>
							<%= link_to '修改密碼', edit_registration_path(:user), class:"btn btn-block btn-sm btn-info" %><br>
							<% if current_user.has_role?(:sale) %>
							<%= link_to '新增商品', new_item_path, class: "btn btn btn-block btn-success btn-sm"%>	
							<% else %>
							<%= button_to '我要當賣家', usertosale_users_path, class: "btn btn-block btn-primary btn-sm", method: :post %>	
							<% end %>									
						</div>


</div>


	

app/views/users/userfavorite.html.erb
<div class="col-md-2">
        
                <%= render partial: 'users/userpanel' %>	
                
        </div>
        
        
<div class="col-md-10">
        
					<% if current_user.wlists.count > 0 %>
					
					<h3 style="display:inline">我想買的物品</h3>
					<hr>
					<div id="fh5co-board" data-columns>
							<% @current_user.favorites.each do |favorite| %>		
									<div class="item">
										<%= link_to favorite, :remote => true  do %>		
										<div class="animate-box">
											<img src="<%= favorite.picture_url(:thumb) %>" alt="">
										</div>
										<% end %>
												<div class="fh5co-desc">
													<h6><%= favorite.name %></h6>
													<h6><%= favorite.price %>元</h6>
													<!-- <%= truncate(favorite.description, length:15) %><br> -->
													<div id="favorite-<%= favorite.id %>">
															<%= render partial: 'items/favorite', :locals => { :item => favorite, :wlist => @wlists } %>	
													</div>
													<%= link_to '聊聊', conversations_path(recipient_id: favorite.user_id, sender_id: current_user.id, item_id: favorite.id), method: :post, class: "btn btn-outline btn-sm", style:"width:100%" %>
												</div>
									</div>
							<% end %>
					</div>
	
				</div>  	<!-- col-md-6 -->
				<% else %>
				<h4>暫無資料</h4>
				<% end %>

</div>

app/views/users/useritem.html.erb
<div class="col-md-2">
        
                <%= render partial: 'users/userpanel' %>	
                
        </div>
        
        
<div class="col-md-10"><!-- 新增商品 -->
									<% if current_user.has_role?(:sale) || current_user.has_role?(:admin) == true %>
									<h3 style="display:inline">我的商品</h3>
									<hr>
									<!-- 我的商品 -->	
									<div id="fh5co-board" data-columns>
											<% @current_user.item.each do |item| %>				
													<div class="item" id="item-<%= item.id %>">
														<%= link_to item, :remote => true do %>		
														<div class="animate-box">
															<img src="<%= item.picture_url(:thumb) %>" alt="">
														</div>
														<% end %>
																<div class="fh5co-desc">
																	<h6><%= truncate(item.name, length:10) %></h6>
																	<h6><%= item.price %>元</h6>
																	<!-- <%= truncate(item.description, length:15) %><br> -->
																	<%= link_to '修改', edit_item_url(item) , class: "btn btn-info btn-sm",  style:"width:100%" %>
																	<%= link_to '刪除', item_path(item), method: :delete, class: "btn btn-danger btn-sm", data: { confirm: 'Are you sure?' },  :remote => true, style:"width:100%" %>										
																</div>
													</div>
											<% end %>
									</div>
									<% else %>
                                    <% end %>
  </div>