config/routes.rb
Rails.application.routes.draw do  
  devise_for :users
  root to: 'items#index'

  # 商品
  resources :items do
    put :favorite, on: :member
  end


  
  # 使用者
  resources :users do
    collection do
      post :usertosale
      get :userfavorite
      get :useritem
    end
  end



  # 訂單
  resources :orders do
    collection do
      post :addtoorder
    end
  end

   # 聊天
  resources :conversations do
    member do
      post :close
    end
    resources :messages, only: [:create]
  end

  # 後台管理
  namespace :admin do
      resources :items do
        member do        
          post  :publish
          post  :hide
        end
      end
      resources :users do
        member do
          post :nottosale
          post :nottoadmin
          post :tosale
          post :toadmin
        end
      end
  end
  

  mount ActionCable.server => '/cable'  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/item.rb
class Item < ApplicationRecord
    resourcify
    belongs_to :user, optional: true

    has_many :conversations
    has_many :orders

    has_many :wlists, :dependent => :destroy
    has_many :favorited_by, through: :wlists, source: :user

    mount_uploader :picture, PictureUploader    
    
    def user_email
        user.email
    end

    private
    def product_params
      params.require(:item).permit(:picture)
    end
end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController
  before_action :set_admin_item, only: [:show, :edit, :update, :destroy]
  load_and_authorize_resource

  # GET /items
  # GET /items.json

  # def favorite
  #   type = params[:type]
  #   if type == "favorite"
  #           if 
  #             current_user.favorites.include?(@item)
  #           else
  #             current_user.favorites << @item
  #           end
  #   elsif type == "unfavorite"
  #       current_user.favorites.delete(@item)
  #   end
  # end

  def index
    if params[:search]
      @items = Item.where('name LIKE ? OR  category LIKE ?', "%#{params[:search]}%",  "%#{params[:search]}%")
      # session[:conversations] ||= []
      # @conversations = Conversation.all.where(id: @items.ids)
      # @conversations = Conversation.includes(:recipient, :messages).find(session[:conversations])
    else
      @items = Item.all
    end 

  end

  def publish
    @item.status = true
    @item.save
    redirect_to admin_items_path
  end

  def hide
    @item.status = false
    @item.save
    redirect_to admin_items_path
  end

  # GET /items/1
  # GET /items/1.json
  def show
    respond_to do |format|
      format.html
      format.js
    end
  end

  # GET /items/new
  def new
    # @item = Item.new
  end

  # GET /items/1/edit
  def edit
  end

  # POST /items
  # POST /items.json
  # def create
  #   @item = current_user.item.build(admin_item_params)

  #   respond_to do |format|
  #     if @item.save
  #       format.html { redirect_to users_path, notice: '商品建立成功' }
  #       # format.json { render :show, status: :created, location: @item }
  #     else
  #       format.html { render :new }
  #       format.json { render json: @item.errors, status: :unprocessable_entity }
  #     end
  #   end
  # end

  # PATCH/PUT /items/1
  # PATCH/PUT /items/1.json
  def update
    respond_to do |format|
      if @item.update(admin_item_params)
        format.html { redirect_to admin_items_path, notice: '商品修改成功' }
        # format.json { render :show, status: :ok, location: @item }
      else
        format.html { render :edit }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /items/1
  # DELETE /items/1.json
  def destroy
    @item.destroy
    respond_to do |format|
      format.html { redirect_to admin_items_path, notice: '成功刪除商品' }
      format.js # destroy.js.erb
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_admin_item
      @item = Item.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def admin_item_params
      params.require(:item).permit(:name, :description, :status, :amount, :price, :picture, :category, :user_id )
    end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :authenticate_user!, :except => [:index, :show]
  before_action :set_item, only: [:show, :edit, :update, :destroy]
  load_and_authorize_resource

  # GET /items
  # GET /items.json

  def favorite
    type = params[:type]
    if type == "favorite"
            if 
              current_user.favorites.include?(@item)
            else
              current_user.favorites << @item
            end
    elsif type == "unfavorite"
        current_user.favorites.delete(@item)
    end
  end

  def index
    if params[:search]
      @items = Item.where('name LIKE ? OR  category LIKE ?', "%#{params[:search]}%",  "%#{params[:search]}%")
      # session[:conversations] ||= []
      # @conversations = Conversation.all.where(id: @items.ids)
      # @conversations = Conversation.includes(:recipient, :messages).find(session[:conversations])
    else
      # @items = Item.full_joins(:orders).where.not(orders: {status: 2} )
      # @items = Item.joins('LEFT OUTER JOIN "orders"').where(orders: {status: 2} )
      # @items = Order.joins("LEFT JOIN items ON items.id = orders.item_id ").where.not(orders: {status: 2} )
      @items = Item.all.where(status: true) 
    end 


  end

  # GET /items/1
  # GET /items/1.json
  def show
    respond_to do |format|
      format.html
      format.js
    end
  end

  # GET /items/new
  def new
    @item = Item.new
  end

  # GET /items/1/edit
  def edit
  end

  # POST /items
  # POST /items.json
  def create
    @item = current_user.item.build(item_params)

    respond_to do |format|
      if @item.save
        format.html { redirect_to users_path, notice: '商品建立成功' }
        # format.json { render :show, status: :created, location: @item }
      else
        format.html { render :new }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /items/1
  # PATCH/PUT /items/1.json
  def update
    respond_to do |format|
      if @item.update(item_params)
        format.html { redirect_to users_path, notice: '商品修改成功' }
        # format.json { render :show, status: :ok, location: @item }
      else
        format.html { render :edit }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /items/1
  # DELETE /items/1.json
  def destroy
    @item.destroy
    respond_to do |format|
      # format.html { redirect_to :back, notice: '成功刪除商品' }
      format.js # destroy.js.erb
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_item
      @item = Item.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def item_params
      params.require(:item).permit(:name, :description, :status, :amount, :price, :picture, :category, :user_id )
    end
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/items/_event.html.erb
<style media="screen">
        b, strong{
          font-size: 15px;
        }

        .span2{
          color: #000;
        }
      </style>
      
      <!-- <p id="notice"><%= notice %></p> -->
      
      <!-- Modal -->
        <div class="modal-dialog" role="document">
          <div class="modal-content">
            <div class="modal-header" style="background-color:#fff;">
              <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
              <h5 class="modal-title" id="myModalLabel" style="color:#000" ><%= @item.name%></h5>              
            </div>

            <div class="modal-body">

                <div class="row">
                    <div class="col-md-6 product_img">
                        <%= image_tag @item.picture, class: "img-responsive"%>                        
                    </div>
                    <div class="col-md-6 product_content">
                        <h4>商品名稱: <span><%= @item.name%></span></h4>
                        <div class="rating">
                            <span class="glyphicon glyphicon-star"></span>
                            <span class="glyphicon glyphicon-star"></span>
                            <span class="glyphicon glyphicon-star"></span>
                            <span class="glyphicon glyphicon-star"></span>
                            <span class="glyphicon glyphicon-star"></span>
                            (10 reviews)
                        </div>

                        <p><b>分類：</b><span class="span2"> <%= @item.category %></span></p>
                        <p><b>狀態：</b><span class="span2"> <%=  @item.status %></span></p>
                        <p>價格：<span class="span2"><span class="glyphicon glyphicon-usd"></span><%=  @item.price %></span></p>
                        <div class="btn-ground">
                            <% if current_user.blank? %>
                                <%= link_to '喜歡', new_session_path(:user), class: "btn btn-primary btn-sm" %>
                            <% else %>
                                <div id="favorite-<%= item.id %>-<%= item.id %>">
                                  <%= render partial: 'favorite', :locals => { :item => item } %>													
                                </div>
                            <% end %>
                            <% if current_user.blank? || current_user.id == item.user_id %>
                            <p>您的商品</p>
                            <% else %>
                            <%= link_to '聊聊', conversations_path(recipient_id: item.user_id, sender_id: current_user.id, item_id: item.id), method: :post, class: "btn btn-success btn-sm", style:"width:100%" %>
                            <% end %>
                        </div>

                  </div>
            </div>
          </div>

          <div class="modal-body"> 

                  <p><%= @item.description.gsub(/\n/, '<br>').html_safe %></p>

          </div>

        </div>

app/views/items/_favorite.html.erb
<% if current_user.favorites.include?(item) %>
    <%= link_to  favorite_item_path(item, type: "unfavorite"), method: :put , remote: true, style:"display:inline" do %>
    <span class="glyphicon glyphicon-heart" style="font-size: 15px; letter-spacing: 5px;"><span style="font-size: 17px;"><%= item.wlists.count.to_s %></span></span>
    <% end %>
    
<% else %>
    <%= link_to  favorite_item_path(item, type: "favorite"), method: :put , remote: true, style:"display:inline"  do %>
    <span class="glyphicon glyphicon-heart-empty" style="font-size: 15px; letter-spacing: 5px;"><span style="font-size: 17px;"><%= item.wlists.count.to_s %></span></span>
    <% end %>    
<% end %>

app/views/items/_form.html.erb
<style>

    .file-upload-wrapper {
      position: relative;
      width: 100%;
      height: 60px;
    }
    .file-upload-wrapper:after {
      content: attr(data-text);
      font-size: 12px;
      position: absolute;
      top: 0;
      left: 0;
      background: #fff;
      padding: 1px 5px;
      display: block;
      width: calc(100% - 40px);
      pointer-events: none;
      z-index: 20;
      height: 40px;
      line-height: 40px;
      color: #999;
      border-radius: 5px 10px 10px 5px;
      font-weight: 300;
    }
    .file-upload-wrapper:before {
      content: '上傳';
      position: absolute;
      top: 0;
      right: 0;
      display: inline-block;
      height: 40px;
      background: #DE5E59;
      color: #fff;
      font-weight: 400;
      z-index: 25;
      font-size: 16px;
      line-height: 42px;
      padding: 0 15px;
      text-transform: uppercase;
      pointer-events: none;
      border-radius: 0 5px 5px 0;
    }
    .file-upload-wrapper:hover:before {
      background: #cc6666;
    }
    .file-upload-wrapper input {
      opacity: 0;
      position: absolute;
      top: 0;
      right: 0;
      bottom: 0;
      left: 0;
      z-index: 99;
      height: 40px;
      margin: 0;
      padding: 0;
      display: block;
      cursor: pointer;
      width: 100%;
    }

</style>

<%= form_with(model: item, local: true, :html =>{:multipart => true} ) do |form| %>
  <% if item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(item.errors.count, "error") %> prohibited this item from being saved:</h2>

      <ul>
      <% item.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

<div class="row">

  <div class="col-md-6">

      <div class="field">
          <%= form.label :商品圖片： %><br>
          <%= form.file_field :picture, id: :item_picture, onchange: "readURL(this);", class:"btn btn-primary" %>
            <img id="img_prev" src="#" />
      </div>

      <script>
          function readURL(input) {
            if (input.files && input.files[0]) {
              var reader = new FileReader();
 
    
              reader.onload = function (e) {
                $('#img_prev')
                  .attr('src', e.target.result)
                  .width("100%")
                  .height("100%");
              };
              reader.readAsDataURL(input.files[0]);
            }
          }
        </script>

  </div>

  <div class="col-md-6">

    <div class="form-group">
     <%= form.label :商品名稱： %>
     <%= form.text_field :name, id: :item_name,:class => 'form-control' %>
    </div>

<div class="row">
    <div class="form-group col-xs-6">
        <%= form.label :商品分類： %>
        <%= form.select 'category', options_for_select(["二手書", "服務、票券", "居家生活", "男女包鞋服飾", "3C數位周邊","其他類別" ],"其他類別"), {}, :class => 'form-control' %>
    </div>

    <div class="form-group col-xs-6">
      <%= form.label :商品狀態： %>
      <%= form.select 'status', options_for_select(["全新", "二手"]), {}, :class => 'form-control' %>
    </div>
</div>

<div class="row">
    <div class="form-group col-xs-6">
      <%= form.label :商品數量： %>
      <%= form.number_field :amount, id: :item_amount,:class => 'form-control' %>
    </div>

    <div class="form-group col-xs-6">
      <%= form.label :商品價格： %>
      <%= form.number_field :price, id: :item_price,:class => 'form-control' %>
  </div>
</div>


    <div class="form-group">
      <%= form.label :商品描述： %>
      <%= form.text_area :description, id: :item_description,:class => 'form-control' %>
    </div><br>


    <div class="actions">
      <%= form.submit "更新" ,class: "btn btn-primary btn-sm"%>
      <%= link_to '返回', items_path ,class: "btn btn-primary btn-sm" %>      
   </div>

  </div>

</div>
<% end %>

app/views/items/destroy.js.erb
$("#item-<%= @item.id %>").remove();
$("#notice").html("<%= flash[:notice] %>");

app/views/items/edit.html.erb
<h1>修改商品</h1>

<%= render 'form', item: @item %>

app/views/items/favorite.js.erb
$("#favorite-<%= @item.id %>").html("<%= escape_javascript(render :partial => 'favorite', :locals => { :item => @item, :wlist => @wlists  }) %>");

$("#favorite-<%= @item.id %>-<%= @item.id %>").html("<%= escape_javascript(render :partial => 'favorite', :locals => { :item => @item, :wlist => @wlists  }) %>");

app/views/items/index.html.erb
<style>

		.stylish-input-group .input-group-addon{
			background-color:transparent;
			border:none;
		}
		.stylish-input-group .form-control{
			background-color:transparent;
			border:none;
			font-size:17px;
			border-radius:0px;
			margin-top:5px;
            margin-bottom:5px
		}
		.stylish-input-group button{
			border:none;
			background:transparent;
			border-radius:0px;			
		}
		 .hr-xs
		{
		  margin-top:-10px;
		  margin-bottom:5px
		}

</style>		
<%= form_tag(items_path, :method => "get") do %>							
<div class="row">
		<div class="col-md-12">
			<div id="imaginary_container"> 
				<div class="input-group stylish-input-group input-append">
					<%= text_field_tag :search, params[:search], placeholder: "商品 分類",  class: "form-control"%>		
					<span class="input-group-addon">
						<button type="submit">
							<span class="glyphicon glyphicon-search"></span>
						</button>  
					</span>		
				</div>
				<hr class="hr-xs">							
			</div>
		</div>
		<div class="col-md-12">
			<a href="?utf8=✓&search=二手書&commit=搜尋" class="btn btn-sm btn-primary">二手書類</a>
			<a href="?utf8=✓&search=服務、票券&commit=搜尋" class="btn btn-sm btn-success">服務、票券</a>
			<a href="?utf8=✓&search=居家生活&commit=搜尋" class="btn btn-sm btn-info">居家生活</a>	
			<a href="?utf8=✓&search=男女包鞋服飾&commit=搜尋" class="btn btn-sm btn-danger">男女包鞋服飾</a>
			<a href="?utf8=✓&search=3C數位&commit=搜尋" class="btn btn-sm btn-warning">3C數位周邊</a>
			<a href="?utf8=✓&search=其他類別&commit=搜尋" class="btn btn-sm btn-success">其他類別</a>
		</div>
	</div>

	<% end %>

					
<div class="row">
			<div id="fh5co-board" data-columns>
					<% @items.each do |item| %>
			
					
							<div class="item">
								<%= link_to item, :remote => true, data: {toggle: "modal", target: "#myModal"} do %>		
								<div class="animate-box">
									<img src="<%= item.picture %>" alt="" width="100%">
								</div>
								<% end %>
										<div class="fh5co-desc">
											<h6 class="fh5co-item-title"><%= truncate(item.name, length:18) %></h6>
											<h6><%= item.price %>元</h6>
											<!-- <%= truncate(item.description, length:15) %> -->
											<div class="btn-ground">
													<% if current_user.blank? %>
													<%= link_to '喜歡', new_session_path(:user), class: "btn btn-outline btn-sm", style:"width:100%" %>
													<% else %>
													<% if current_user.id == item.user_id %>
													<p>您的商品</p>
													<% else %>
													<div id="favorite-<%= item.id %>">
														<%= render partial: 'favorite', :locals => { :item => item, :wlist => @wlists } %>	
													</div>
													<%= link_to '聊聊', conversations_path(recipient_id: item.user_id, sender_id: current_user.id, item_id: item.id), method: :post, class: "btn btn-outline btn-sm", style:"width:100%" %>
													<% end %>
												<% end %>
											</div>
										</div>
							</div>
					<% end %>
			</div>
</div>






<!-- Modal -->
<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
	</div> 

app/views/items/new.html.erb
<h1>新增商品</h1>

<%= render 'form', item: @item %>

app/views/items/show.html.erb
<style>
    .carousel {
      margin-top: 20px;
  }
  .carousel-link .thumb {
    width: 25%;
    cursor: pointer;
    float: left;
  }
  .carousel-link .thumb img {
    width: 100%;
    margin: 2px;
  }
  .carousel-link .thumb:first-of-type img {
    margin-left: 0;
  }
  .carousel-link .thumb:last-of-type img {
    margin-right: 0;
  }
  .item img {
    width: 100%;	
  }
  
</style>

<div class="put-it-center">
<p id="notice"><%= notice %></p>



<div class="container">
    <div class="row">
      <div class="col-sm-6">
          <div id="carousel" class="carousel slide" data-ride="carousel">
              <div class="carousel-inner">
                  <div class="item active">
                      <img src="<%= @item.picture %>">
                  </div>
                  <div class="item">
                      <img src="http://placehold.it/350x250/00ffff/000&text=Product+Image+2">
                  </div>
                  <div class="item">
                      <img src="http://placehold.it/350x250/ff00ff/fff&text=Product+Image+3">
                  </div>
                  <div class="item">
                      <img src="http://placehold.it/350x250/ffff00/000&text=Product+Image+4">
                  </div>
              </div>
              <div class="clearfix">
                <div class="carousel-link">
                  <div data-target="#carousel" data-slide-to="0" class="thumb"><img src="<%= @item.picture %>"></div>
                  <div data-target="#carousel" data-slide-to="1" class="thumb"><img src="http://placehold.it/100/00ffff/000&text=Product+Image+2"></div>
                  <div data-target="#carousel" data-slide-to="2" class="thumb"><img src="http://placehold.it/100/ff00ff/fff&text=Product+Image+3"></div>
                  <div data-target="#carousel" data-slide-to="3" class="thumb"><img src="http://placehold.it/100/ffff00/000&text=Product+Image+4"></div>
                </div>
              </div>
          </div> 
      </div> <!-- /col-sm-6 -->
      <div class="col-sm-6">
          <h2><%= @item.name %></h2>
          <h4><%= @item.category %></h4>
          <h4><%= @item.status %></h4>
          <h4><%= @item.amount %></h4>
          <h3><%= @item.price %></h3>
          <p><%= @item.description %></p>
      </div> <!-- /col-sm-6 -->
    </div> <!-- /row -->
  </div> <!-- /container -->



<!-- <%= link_to '修改', edit_item_path(@item) %> | -->
<%= link_to '返回', items_path, class: "btn btn-primary btn-sm" %>
</div>

app/views/items/show.js.erb
  
$('#myModal').html("<%= escape_javascript(render :partial => 'event', :locals => { :item => @item }) %>");
  $('#myModal').modal('show');

  // $('#myModal').modal({
  //   focus: true,
  //   show: true
  // });
// ('#myModal').on('show.bs.modal', function () {
//   $('#myModal').modal({
//     focus: true,
//     show: true
//   })
//  });

// $('#myModal').on('hidden.bs.modal', function () {
//    $('#myModal .modal-content').empty();
//  });