config/routes.rb
Rails.application.routes.draw do  
  devise_for :users
  root to: 'items#index'

  # 商品
  resources :items do
    put :favorite, on: :member
  end


  
  # 使用者
  resources :users do
    collection do
      post :usertosale
      get :userfavorite
      get :useritem
    end
  end



  # 訂單
  resources :orders do
    collection do
      post :addtoorder
    end
  end

   # 聊天
  resources :conversations do
    member do
      post :close
    end
    resources :messages, only: [:create]
  end

  # 後台管理
  namespace :admin do
      resources :items do
        member do        
          post  :publish
          post  :hide
        end
      end
      resources :users do
        member do
          post :nottosale
          post :nottoadmin
          post :tosale
          post :toadmin
        end
      end
  end
  

  mount ActionCable.server => '/cable'  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/_slide.html.erb
<header>
    <div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">
      <ol class="carousel-indicators">
        <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
        <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
        <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
      </ol>
      <div class="carousel-inner" role="listbox">
        <!-- Slide One - Set the background image for this slide in the line below -->
        <div class="carousel-item active" style="background-image: url('https://s-media-cache-ak0.pinimg.com/originals/86/0e/c3/860ec3edaa6bb1b93775b8aeed6313c0.jpg')">
          <div class="carousel-caption d-none d-md-block">
            <h3>First Slide</h3>
            <p>This is a description for the first slide.</p>
          </div>
        </div>
        <!-- Slide Two - Set the background image for this slide in the line below -->
        <div class="carousel-item" style="background-image: url('https://s-media-cache-ak0.pinimg.com/originals/f8/d5/08/f8d5084f01f9663a0757935af6dccb2f.jpg')">
          <div class="carousel-caption d-none d-md-block">
            <h3>Second Slide</h3>
            <p>This is a description for the second slide.</p>
          </div>
        </div>
        <!-- Slide Three - Set the background image for this slide in the line below -->
        <div class="carousel-item" style="background-image: url('https://s-media-cache-ak0.pinimg.com/originals/f8/d5/08/f8d5084f01f9663a0757935af6dccb2f.jpg')">
          <div class="carousel-caption d-none d-md-block">
            <h3>Third Slide</h3>
            <p>This is a description for the third slide.</p>
          </div>
        </div>
      </div>
      <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
        <span class="sr-only">Previous</span>
      </a>
      <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
        <span class="carousel-control-next-icon" aria-hidden="true"></span>
        <span class="sr-only">Next</span>
      </a>
    </div>
  </header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>貳拍</title>
    <%= csrf_meta_tags %> 
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no, maximum-scale=1, user-scalable=no">  

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= action_cable_meta_tag %>
    
    
    <!-- Google Webfonts -->
    <link href='http://fonts.googleapis.com/css?family=Roboto:400,300,100,500' rel='stylesheet' type='text/css'>
    <link href='https://fonts.googleapis.com/css?family=Montserrat:400,700' rel='stylesheet' type='text/css'>
    
    
    <!-- Animate.css  -->
    <link rel="stylesheet" href="/css/animate.css">
    <!-- Icomoon Icon Fonts-->
    <link rel="stylesheet" href="/css/icomoon.css">
    <!-- Magnific Popup -->
    <link rel="stylesheet" href="/css/magnific-popup.css">
    <!-- Salvattore -->
    <link rel="stylesheet" href="/css/salvattore.css">
    <!-- Theme Style -->
    <link rel="stylesheet" href="/css/style.css">
    <!-- Modernizr JS -->
    <script src="/js/modernizr-2.6.2.min.js"></script>
    <!-- FOR IE9 below -->
    <!--[if lt IE 9]
    <script src="js/respond.min.js"></script>
    [endif] 
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/css/bootstrap.min.css" integrity="sha384-PsH8R72JQ3SOdhVi3uxftmaW6Vc51MKb0q5P2rRUpPvrszuE4W1povHYgTpBfshb" crossorigin="anonymous"> -->

    <style>
        .popupunder{
          width: 300px;
        position:fixed;
        top: 10px;
        right: 10px;
        z-index: 10;
        border: 0;
        padding: 20px;
      }
      .popupunder.alert-success{
          border: 1px solid #8BC34A;
        background:#AED581;
        color:#fff;
      }
      .popupunder.alert-danger{
        border: 1px solid #f44336;
        background:#e57373;
        color:#fff;
      }
      .popupunder .close{
        font-size: 10px;
        position:absolute !important;
        right: 2px;
        top: 3px;
      }
    </style>
  </head>

<body>

    <!-- Navigation -->
    <div id="fh5co-offcanvass">
      <a href="#" class="fh5co-offcanvass-close js-fh5co-offcanvass-close">選單 <i class="icon-cross"></i> </a>
      <h1 class="fh5co-logo"><%= link_to '貳拍' , root_url, class: "navbar-brand"%></h1>            
      <ul>
          <% if current_user %>
              <% if current_user.has_role?(:admin) %>
                <li><b><%= link_to '後台', admin_users_path %></b></li>
              <% end %>
            <li><%= link_to '我的帳號', users_path %></li>
              <% if current_user.has_role?(:sale) || current_user.has_role?(:admin) %>
              <li><%= link_to '我要賣', new_item_path %></li>            
              <% end %>
            <li><%= link_to '聊聊購買', conversations_path %></li>
            <!-- <li>我的商品</li> -->
            <li><%= link_to '登出', destroy_user_session_path, :method => :delete %></li>    
          <% else %>
            <li><%= link_to '註冊', new_registration_path(:user) %></li>
            <li><%= link_to '登入', new_session_path(:user) %></li>
          <% end %>
      </ul>
      <h3 class="fh5co-lead">聯絡我們</h3>
      <p class="fh5co-social-icons">

        <a href="#"><i class="icon-facebook"></i></a>
        <a href="#"><i class="icon-instagram"></i></a>
        <a href="#"><i class="icon-youtube"></i></a>
      </p>
    </div>
    <header id="fh5co-header" role="banner">
      <div class="container">
        <div class="row">
          <div class="col-md-12">
            <a href="#" class="fh5co-menu-btn js-fh5co-menu-btn"> <i class="icon-menu"></i></a>
            <%= link_to '貳拍' , root_url, class: "navbar-brand"%>
          </div>
        </div>
      </div>
    </header>

    

    <div id="fh5co-main">
        <div class="container">

          <% if notice %>
            <div class="popupunder alert alert-success fade in"><button type="button" class="close close-sm" data-dismiss="alert"><i class="glyphicon glyphicon-remove"></i></button><strong>好消息 : </strong><%= notice %></div>            
          <% end %>
          <% if alert %>
            <div class="popupunder alert alert-danger fade in"><button type="button" class="close close-sm" data-dismiss="alert"><i class="glyphicon glyphicon-remove"></i></button><strong>壞消息 : </strong><%= alert %></div>            
          <% end %>

          <%= yield %>
        </div>
    </div>

    <footer id="fh5co-footer">
      
      <div class="container">
        <div class="row row-padded">
          <div class="col-md-12 text-center">
            <p class="fh5co-social-icons">

              <a href="#"><i class="icon-facebook"></i></a>
              <a href="#"><i class="icon-instagram"></i></a>
              <a href="#"><i class="icon-youtube"></i></a>
            </p>
            <p><small>&copy; by SHUEA</small></p>
          </div>
        </div>
      </div>
    </footer>



    	<!-- jQuery -->
	<script src="/js/jquery.min.js"></script>
	<!-- jQuery Easing -->
	<script src="/js/jquery.easing.1.3.js"></script>
	<!-- Bootstrap -->
	<script src="/js/bootstrap.min.js"></script>
	<!-- Waypoints -->
	<script src="/js/jquery.waypoints.min.js"></script>
	<!-- Magnific Popup -->
	<script src="/js/jquery.magnific-popup.min.js"></script>
	<!-- Salvattore -->
	<script src="/js/salvattore.min.js"></script>
	<!-- Main JS -->
  <script src="/js/main.js"></script>
  
  <script type="text/javascript">

    $('.popovers').popover();
    window.setTimeout(function() {
    $(".alert").fadeTo(2000, 500).slideUp(500, function(){
    $(this).remove(); 
    });
    // 500 : Time will remain on the screen
    }, 500);

    </script>

    <!-- <script src="//cdnjs.cloudflare.com/ajax/libs/jquery/2.1.3/jquery.min.js"></script> -->
    <!-- <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script> -->
    <!-- <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.3/umd/popper.min.js" integrity="sha384-vFJXuSJphROIrBnz7yo7oB41mKfc8JzQZiCq4NCceLEaO4IHwicKwpJf9c9IpFgh" crossorigin="anonymous"></script> -->
    <!-- <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/js/bootstrap.min.js" integrity="sha384-alpBpkh1PFOepccYVYDB4do5UnbKysX5WZXm3XxPqe5iKTfUKjNkCk9SaVuEZflJ" crossorigin="anonymous"></script> -->

  </body>
</html>